const state={items:[],type:'전체',sort:'recent'};const $=s=>document.querySelector(s),q=$('#q'),grid=$('#grid'),count=$('#count'),types=$('#types'),sorts=$('#sorts'),clear=$('#clear');
const esc=s=>String(s??'').replace(/[&<>'"]/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;',"'":'&#39;','"':'&quot;'}[c]));
const icons={GitHub:'⌘',도구:'◇',프롬프트:'✦',논문:'▤',영상:'▷',가이드:'↗'};
function filtered(){const term=q.value.trim().toLocaleLowerCase('ko');return state.items.filter(x=>(state.type==='전체'||x.type===state.type)&&(!term||[x.title,x.summary,...(x.tags||[]),...(x.categories||[]),...(x.content||[])].join(' ').toLocaleLowerCase('ko').includes(term))).sort((a,b)=>state.sort==='important'?b.importance-a.importance:state.sort==='title'?a.title.localeCompare(b.title,'ko'):b.updated.localeCompare(a.updated));}
function render(){const list=filtered();count.textContent=list.length;grid.classList.remove('refresh');void grid.offsetWidth;grid.classList.add('refresh');grid.innerHTML=list.map((x,i)=>`<a class="card type-${esc(x.type)} ${x.importance>=5?'featured':''}" href="knowledge.html?id=${encodeURIComponent(x.id)}"><span class="card-motif" aria-hidden="true">${i%3===0?'✦':i%3===1?'●':'〰'}</span><div class="card-top"><span class="type-icon" aria-hidden="true">${icons[x.type]||'•'}</span><span class="pill">${esc(x.type)}</span><span class="status">${esc(x.status)}</span></div><h3>${esc(x.title)}</h3><p>${esc(x.summary)}</p><div class="tags">${(x.tags||[]).slice(0,3).map(t=>`<span>#${esc(t)}</span>`).join('')}</div><div class="card-foot"><time>${esc(x.updated)}</time><span class="arrow" aria-hidden="true">↗</span></div></a>`).join('')||`<div class="empty"><span aria-hidden="true">◇</span><h3>아직 맞는 카드가 없어요</h3><p>검색어를 짧게 바꾸거나 선택한 필터를 지워보세요.</p><button type="button" onclick="document.querySelector('#clear').click()">모두 다시 보기</button></div>`;}
function makeFilters(){types.innerHTML=['전체',...new Set(state.items.map(x=>x.type))].map((t,i)=>`<button class="${i?'':'active'}" data-type="${esc(t)}"><span aria-hidden="true">${t==='전체'?'□':icons[t]||'•'}</span>${esc(t)}</button>`).join('')}
function reset(){state.type='전체';q.value='';types.querySelectorAll('button').forEach((b,i)=>b.classList.toggle('active',i===0));render()}
types.addEventListener('click',e=>{const b=e.target.closest('button');if(!b)return;types.querySelectorAll('button').forEach(x=>x.classList.remove('active'));b.classList.add('active');state.type=b.dataset.type;render()});sorts.addEventListener('click',e=>{const b=e.target.closest('button');if(!b)return;sorts.querySelectorAll('button').forEach(x=>x.classList.remove('active'));b.classList.add('active');state.sort=b.dataset.sort;render()});q.addEventListener('input',render);clear.addEventListener('click',reset);document.addEventListener('keydown',e=>{if((e.metaKey||e.ctrlKey)&&e.key.toLowerCase()==='k'){e.preventDefault();q.focus()}});
fetch('data/knowledge.json').then(r=>{if(!r.ok)throw Error();return r.json()}).then(d=>{state.items=d;makeFilters();render()}).catch(()=>grid.innerHTML='<div class="empty"><h3>자료를 불러오지 못했습니다</h3><p>잠시 후 다시 시도해 주세요.</p></div>');
