import fs from 'node:fs'; import path from 'node:path';
const root=path.resolve('.'), base='https://techkwon.github.io/ai-knowledge-portal/';
const items=JSON.parse(fs.readFileSync(path.join(root,'data/knowledge.json'),'utf8'));
const esc=s=>String(s??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const json=s=>JSON.stringify(s).replace(/</g,'\\u003c');
const head=({title,description,url,type='website'})=>`<meta charset="UTF-8"><meta name="viewport" content="width=device-width,initial-scale=1"><title>${esc(title)}</title><meta name="description" content="${esc(description)}"><meta name="robots" content="index,follow,max-image-preview:large"><link rel="canonical" href="${url}"><link rel="icon" href="${base}assets/favicon.svg" type="image/svg+xml"><link rel="apple-touch-icon" href="${base}assets/chagok-mascot.png"><meta property="og:locale" content="ko_KR"><meta property="og:type" content="${type}"><meta property="og:site_name" content="차곡 AI"><meta property="og:title" content="${esc(title)}"><meta property="og:description" content="${esc(description)}"><meta property="og:url" content="${url}"><meta property="og:image" content="${base}assets/chagok-og.png"><meta property="og:image:width" content="1200"><meta property="og:image:height" content="630"><meta name="twitter:card" content="summary_large_image"><meta name="twitter:title" content="${esc(title)}"><meta name="twitter:description" content="${esc(description)}"><meta name="twitter:image" content="${base}assets/chagok-og.png"><link rel="stylesheet" href="${base}styles.css">`;
const header=`<header><a class="brand" href="${base}"><span class="logo" aria-hidden="true">ㅋ</span><span>차곡 AI</span></a><nav><a href="${base}">자료 둘러보기</a><a href="${base}about.html">이곳은?</a></nav></header>`;
const footer=`<footer><strong>차곡 AI</strong><span>개인정보 없이, 다시 쓸 수 있는 지식만 남깁니다.</span></footer>`;
const staticCards=items.sort((a,b)=>b.updated.localeCompare(a.updated)).map((x,i)=>`<a class="card type-${esc(x.type)} ${x.importance>=5?'featured':''}" href="knowledge/${encodeURIComponent(x.id)}/" data-id="${esc(x.id)}"><span class="card-motif" aria-hidden="true">${i%3===0?'✦':i%3===1?'●':'〰'}</span><div class="card-top"><span class="type-icon" aria-hidden="true">${({GitHub:'⌘',도구:'◇',프롬프트:'✦',논문:'▤',영상:'▷',가이드:'↗'})[x.type]||'•'}</span><span class="pill">${esc(x.type)}</span><span class="status">${esc(x.status)}</span></div><h3>${esc(x.title)}</h3><p>${esc(x.summary)}</p><div class="tags">${(x.tags||[]).slice(0,3).map(t=>`<span>#${esc(t)}</span>`).join('')}</div><div class="card-foot"><time datetime="${esc(x.updated)}">${esc(x.updated)}</time><span class="arrow" aria-hidden="true">↗</span></div></a>`).join('');
let index=fs.readFileSync(path.join(root,'index.html'),'utf8');
index=index.replace(/<head>[\s\S]*?<\/head>/,`<head>${head({title:'차곡 AI | AI 도구·GitHub·프롬프트 지식 아카이브',description:'AI 도구, GitHub 프로젝트, 프롬프트와 교육 활용법을 검색하고 다시 찾기 쉽게 정리한 한국어 지식 아카이브',url:base})}<script type="application/ld+json">${json({'@context':'https://schema.org','@type':'WebSite',name:'차곡 AI',url:base,description:'AI 도구와 활용법을 정리한 한국어 지식 아카이브',potentialAction:{'@type':'SearchAction',target:base+'?q={search_term_string}','query-input':'required name=search_term_string'}})}</script></head>`).replace(/<section class="grid" id="grid"[^>]*>[\s\S]*?<\/section>/,`<section class="grid" id="grid" aria-live="polite">${staticCards}</section>`);
fs.writeFileSync(path.join(root,'index.html'),index);
for(const x of items){const dir=path.join(root,'knowledge',x.id);fs.mkdirSync(dir,{recursive:true});const url=base+'knowledge/'+encodeURIComponent(x.id)+'/';const refs=[...new Set([x.url,...(x.sourceEvidence||[])].filter(Boolean))];const html=`<!doctype html><html lang="ko"><head>${head({title:`${x.title} | 차곡 AI`,description:x.summary,url,type:'article'})}<meta property="article:published_time" content="${x.updated}"><script type="application/ld+json">${json({'@context':'https://schema.org','@type':'TechArticle',headline:x.title,description:x.summary,dateModified:x.updated,inLanguage:'ko-KR',mainEntityOfPage:url,keywords:(x.tags||[]).join(', '),image:base+'assets/chagok-og.png',publisher:{'@type':'Organization',name:'차곡 AI',url:base}})}</script></head><body>${header}<main><article class="detail"><a class="back" href="${base}">← 모든 카드 보기</a><div class="meta"><span class="pill">${esc(x.type)}</span><span class="status">${esc(x.status)}</span></div><h1>${esc(x.title)}</h1><p class="lead">${esc(x.summary)}</p><div class="tags">${(x.tags||[]).map(t=>`<span>#${esc(t)}</span>`).join('')}</div><hr><h2>무엇을 할 수 있나요?</h2>${(x.content||[]).map(p=>`<p>${esc(p)}</p>`).join('')}${(x.cautions||[]).length?`<aside class="caution"><strong>살펴볼 점</strong><ul>${x.cautions.map(v=>`<li>${esc(v)}</li>`).join('')}</ul></aside>`:''}<h2>공식 자료</h2><div class="sources">${refs.map((u,i)=>`<a class="source" href="${esc(u)}" target="_blank" rel="noreferrer">${i?'관련 자료':'공식 페이지'} 열기 ↗</a>`).join('')}</div></article></main>${footer}</body></html>`;fs.writeFileSync(path.join(dir,'index.html'),html)}
const urls=[base,base+'about.html',...items.map(x=>base+'knowledge/'+encodeURIComponent(x.id)+'/')];fs.writeFileSync(path.join(root,'sitemap.xml'),`<?xml version="1.0" encoding="UTF-8"?>\n<urlset xmlns="http://www.sitemaps.org/schemas/sitemap/0.9">\n${urls.map(u=>`  <url><loc>${esc(u)}</loc><changefreq>${u===base?'weekly':'monthly'}</changefreq><priority>${u===base?'1.0':'0.7'}</priority></url>`).join('\n')}\n</urlset>\n`);fs.writeFileSync(path.join(root,'robots.txt'),`User-agent: *\nAllow: /\nSitemap: ${base}sitemap.xml\n`);fs.writeFileSync(path.join(root,'404.html'),`<!doctype html><html lang="ko"><head>${head({title:'페이지를 찾지 못했어요 | 차곡 AI',description:'요청한 지식 카드를 찾을 수 없습니다.',url:base+'404.html'})}</head><body>${header}<main><div class="empty"><h1>카드를 찾지 못했어요</h1><p>주소가 바뀌었거나 자료가 정리되었을 수 있습니다.</p><a class="source" href="${base}">모든 카드 보기</a></div></main>${footer}</body></html>`);console.log({items:items.length,urls:urls.length});
